### ISSUE TITLE
Latest version produces zero results in Comunica LTQP

### ISSUE THREAD

**Issue by smessie** [comunica/rdf-streaming-store.js#8]
When using [`@comunica/query-sparql-link-traversal`](https://www.npmjs.com/package/@comunica/query-sparql-link-traversal) and [`@comunica/query-sparql-link-traversal-solid`](https://www.npmjs.com/package/@comunica/query-sparql-link-traversal-solid) which uses this package, no results are returned (even though link traversal is happening -- confirmed with the network tab when using LTQP in the browser, and also confirmed via the command line).

When you manually change the version of this dependency back to 1.1.0 instead of 1.1.1, it produces the expected results again.

You can manually produce the bug by following following steps:
1. Clone any of the 2 LTQP packages from above
2. Remove the `yarn.lock` file (and node_modules if you would not have just cloned the repo)
3. Run `yarn install` to get the latest version of all dependencies
4. Run any query locally
5. Notice it produces no results
6. Downgrade the version of this library to 1.1.0 by changing the yarn.lock

Change 
```
rdf-streaming-store@^1.1.0:
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/rdf-streaming-store/-/rdf-streaming-store-1.1.1.tgz#f6f77dbf652eab8e2321cfb8e37d7826e34c97a2"
  integrity sha512-CuvxiADXqPYvknz2/ToNYKKlB3wR+p+JXa0KrYWhMSmAYvMZiwLO8Nb2zwEic67Vfk5MjDBRbu7i6pm2ZsP1iA==
  dependencies:
    "@rdfjs/types" "*"
    "@types/n3" "^1.10.4"
    "@types/readable-stream" "^2.3.15"
    n3 "^1.16.3"
    rdf-string "^1.6.2"
    rdf-terms "^1.9.1"
    readable-stream "^4.3.0"
```
to
```
rdf-streaming-store@^1.1.0:
  version "1.1.0"
  resolved "https://registry.yarnpkg.com/rdf-streaming-store/-/rdf-streaming-store-1.1.0.tgz#a00be02eeb1616e577a095dad9afe96d9106fcfa"
  integrity sha512-C/5NTKGpKrNJ5VUo42DtGFsXYDlP3rx/u4C6gEBuSn+6eVFahjFdUDgNGcPtVyhCQkctRCj3GT1lX9UeyoXWtw==
  dependencies:
    "@rdfjs/types" "*"
    "@types/n3" "^1.10.4"
    "@types/readable-stream" "^2.3.15"
    n3 "^1.16.3"
    rdf-string "^1.6.2"
    rdf-terms "^1.9.1"
    readable-stream "^4.3.0"
```
7. Notice it produces the expected results

**Comment by rubensworks** [comment]
Ouch, there must be something different then since last time @surilindur checked @maartyman's PR.
I'll revert the last PR, and release 1.1.2 as fix.

@maartyman Could you have a look to see what could be going wrong? @surilindur can probably help here.
